config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home', to: 'pages#home'

  resources :pets, only: [:index, :show] do
    resources :bookings, only: [:create]
  end

  namespace :owner do
    resources :pets
  end

  resources :bookings, only: [:index, :edit, :update, :destroy, :show]


  get '/profile' => "pages#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["dog", "cat", "ostrich", "monkey", "goat", "rabbit", "hamster", "snake", "rat", "mouse", "chameleon", "swan", "elephant", "pelican", "bird", "tortoise", "gnu", "otter", "pig", "parrot", "lion"].sort
  GENDERS = %w(female male)
  has_many :bookings, dependent: :destroy
  belongs_to :user

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :species, presence: true, inclusion: { in: SPECIES, allow_nil: false }
  validates :title, presence: true
  validates :gender, presence: true, inclusion: { in: GENDERS, allow_nil: false }
  validates :price, presence: true
  validates :description, presence: true, length: { minimum: 6 }
  validates :photo, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pets
  has_many :bookings

  validates :address, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
   before_action :set_booking, only: [:edit, :destroy, :show]

  def create
    @pet = Pet.find(params[:pet_id])
    @booking = Booking.new
    @booking.pet = @pet
    @booking.user = current_user
    @booking.price = @pet.price
    @booking.status = "Confirmed"

    @booking.save
  end

  def index
    @bookings = Booking.all
  end

  def show
  end

  def edit
    @booking.status = "Cancelled"
    @booking.save
    redirect_to bookings_path
  end

  def destroy
    @booking.delete
    redirect_to bookings_path
  end


  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
end

app/controllers/owner/pets_controller.rb
class Owner::PetsController < ApplicationController
  before_action :set_pet, only: [:destroy, :edit, :update, :show]

  def index
    @pets = current_user.pets
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    @pet.address = current_user.address
    if @pet.save
      redirect_to owner_pets_path
    else
      render :new
    end
  end

  def destroy
    @pet.destroy
    redirect_to owner_pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to owner_pets_path
  end

  def show
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :title, :species, :gender, :birth_date,
     :height, :weight, :description, :food, :exercise, :price, :photo, :photo_cache)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @pet = Pet.new
  end

  def profile
    @current_user = current_user
    #params.require(:product).permit(:first_name, :last_name, :address, :photo, :photo_cache)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:pet][:species].present? && params[:pet][:address].present?
      @species = params[:pet][:species]
      @address = (params[:pet][:address]).capitalize

      @pets = Pet.where(species: @species, address: @address)
      if current_user
        @user = current_user
        @pets = @pets.select{ |pet| pet.user_id != @user.id}
      end
      if @pets.length > 0
        @message = "Showing #{@species}s in #{@address}"
      else
        @message = "Sorry, there are currently no #{@species}s available in #{@address}."
      end

    elsif params[:pet][:species].present? && params[:pet][:address].blank?
      @species = params[:pet][:species]
      @pets = Pet.where(species: @species)
      if current_user
        @user = current_user
        @pets = @pets.select{ |pet| pet.user_id != @user.id}
      end
      if @pets.length > 0
        @message = "Showing all #{@species}s"
      else
        @message = "Sorry, there are currently no #{@species}s available."
      end
    elsif params[:pet][:species].blank? && params[:pet][:address].present?
      @address = (params[:pet][:address]).capitalize
      @pets = Pet.where(address: @address)
      if current_user
        @user = current_user
        @pets = @pets.select{ |pet| pet.user_id != @user.id}
      end
      if @pets.length > 0
        @message = "Showing all pets in #{@address}"
      else
        @message = "Sorry, there are currently no pets available in #{@address}."
      end
    elsif params[:pet][:species].blank? && params[:pet][:address].blank?
      @pets = Pet.all

      if current_user
        @user = current_user
        @pets = @pets.select{ |pet| pet.user_id != @user.id}
      end
      if @pets.length > 0
        @message = "Showing all pets"
      else
        @message = "Sorry, there are currently no pets available."
      end
    end

  end

  def show
    @pet = Pet.find(params[:id])
    @booking = Booking.new(pet: @pet, user: current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/create.html.erb
<h1>Woof! It's a date!</h1>

<p>Congratulations! You have booked a pet-session with <b>
  <%= link_to @pet.name, pet_path(@pet), target: "blank" %></b>.</p>
<p>The cost per day for your time with <%= @pet.name %> is <b><%= @pet.price %>€</b>.</p>

<p>Please contact <b><%= @pet.user.first_name %></b> (<%= @pet.user.email %>) to schedule a rendez-vous.</p>



<div class="my-bookings">
  <%= link_to "View my bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-button btn"%>
</div>

app/views/bookings/index.html.erb
<div class="wrapper">

<div class= "title">
<h1> My bookings </h1>
</div>

 <% @bookings.each do |booking| %>
    <% if booking.status == "Confirmed" && booking.user == current_user %>
      <div class="pet-booking">
        <div class="pet-photo">
          <%= cl_image_tag booking.pet.photo %>
        </div>
        <div class="pet-body">
          <h3> <%= booking.pet.name %> </h3>
          <p> <%= booking.pet.price%>€ / day </p>
          <p> Owner: <%= booking.pet.user.first_name %> <%= booking.pet.user.last_name %></p>
        </div>
        <ul class="list-inline pet-actions">
          <li><%= link_to "Cancel", edit_booking_path(booking) %><li>
        </ul>
      </div>
    <% end %>
  <% end %>

<div class= "title">
<h1> My pets' bookings </h1>
</div>

 <% @bookings.each do |booking| %>
    <% if booking.status == "Confirmed" && booking.pet.user == current_user %>
      <div class="pet-booking">
        <div class="pet-photo">
          <%= cl_image_tag booking.pet.photo %>
        </div>
        <div class="pet-body">
          <h3> <%= booking.pet.name %> </h3>
          <p> <%= booking.pet.price%>€ / day </p>
          <p> Renter: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
        </div>
        <ul class="list-inline pet-actions">
          <li><%= link_to "Cancel", edit_booking_path(booking) %><li>
        </ul>
      </div>
    <% end %>
  <% end %>

  <div class= "title">
    <h1> Cancelled bookings </h1>
  </div>

  <% @bookings.each do |booking| %>
  <% if booking.status == "Cancelled" &&  (booking.pet.user == current_user || booking.user == current_user) %>
  <div class="pet-booking">
    <div class="pet-photo">
      <%= cl_image_tag booking.pet.photo %>
    </div>
    <div class="pet-body">
      <h3> <%= booking.pet.name %> </h3>
      <p> <%= booking.pet.price%>€ / day </p>
      <p> Renter: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
      <p> Owner: <%= booking.pet.user.first_name %> <%= booking.pet.user.last_name %></p>
    </div>
    <ul class="list-inline pet-actions">
      <li><%= link_to "Remove", booking_path(booking), method: "delete" %><li>
      </ul>
    </div>
    <% end %>
    <% end %>


  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <script src="https://maps.googleapis.com/maps/api/js?"></script>
  </body>
</html>

app/views/owner/pets/edit.html.erb
<div class="wrapper">

  <div class="container">

  <%= simple_form_for(@pet, url: owner_pet_path(@pet), method: :patch) do |p| %>
    <%= p.error_notification %>
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="card-white">
          <h3>Tell us about your pet</h3>
            <%= p.input :name, placeholder: 'ex: croquette' %>
            <%= p.input :species, priority: ["dog"], collection: Pet::SPECIES %>

          <div class="row">
            <div class="col-xs-12 col-md-6">
              <%= p.input :gender, collection: Pet::GENDERS %>
            </div>
            <div class="col-xs-12 col-md-6">
              <%= p.input :birth_date, start_year: Date.today.year,
                                    end_year: Date.today.year - 90, discard_day: true,
                                    order: [:month, :year] %>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12 col-md-6">
              <%= p.input :height, label: "Height (inches)" %>
            </div>
            <div class="col-xs-12 col-md-6">
              <%= p.input :weight, label: "Weight (kg)" %>
            </div>
          </div>

          <%= p.input :description, placeholder: 'Très gentil chien qui adore jouer au ballon. Attention, il mord de temps en temps.' %>
          <%= p.input :food, collection:["Croquettes Royal Canin", "Croquettes Friskies", "Repas pour humains", "Graines", "Restes de poulet", "Caviar"], as: :check_boxes%>
          <%= p.input :title, label: "Title of your add", hint: "Choose a fun title to attract as many people as possible" %>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="card-white">
          <h3>Pictures</h3>
          <%= cl_image_tag @pet.photo, class:"edit_picture" %>
          <%= p.input :photo %>
          <%= p.input :photo_cache, as: :hidden %>
      </div>
        </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="card-white">
          <h3>Price</h3>
          <%= p.input :price, label: "Daily rental price (€)", hint: '15€ for a nice and beautiful dog, 5€ for an ugly and dangerous cat', input_html: { class: "price_input"}, label_html:{ class: "price_label"}, hint_html:{ class: "price_hint", id: "hint_id"} %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
          <%= p.button :submit, 'Edit my pet !', class: 'button' %>
      </div>
    </div>


  <% end %>
  </div>
</div>

app/views/owner/pets/index.html.erb
<div class="wrapper">

  <div class= "title">
   <h1> My pets </h1>
  </div>

  <% @pets.each do |pet| %>

    <div class="pet">

      <div class="pet-photo">
        <%= cl_image_tag pet.photo %>
      </div>

      <div class="pet-body">
        <h3> <%= pet.name %> </h3>
        <p> <%= pet.title%> </p>
        <p> <%= pet.price%>€ / day </p>
      </div>

      <ul class="list-unstyled pet-actions">
        <li><%= link_to "View", owner_pet_path(pet) %></li>
        <li><%= link_to "Edit", edit_owner_pet_path(pet) %></li>
        <li><%=link_to "Delete", owner_pet_path(pet), method: :delete, data: { confirm: "Are you sure you want to delete #{pet.name} ?" } %> </li>
      </ul>

    </div>

  <% end %>
</div>

app/views/owner/pets/new.html.erb
<div class="wrapper">

  <div class="container">

  <%= simple_form_for(@pet, url: owner_pets_path, method: :post) do |p| %>
    <%= p.error_notification %>
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="card-white">
          <h3>Tell us about your pet</h3>
            <%= p.input :name, placeholder: 'ex: croquette', input_html: { class: "small-text"} %>
            <%= p.input :species, priority: ["dog"], collection: Pet::SPECIES %>

          <div class="row">
            <div class="col-xs-12 col-md-6">
              <%= p.input :gender, collection: Pet::GENDERS %>
            </div>
            <div class="col-xs-12 col-md-6">
              <%= p.input :birth_date, start_year: Date.today.year,
                                    end_year: Date.today.year - 90, discard_day: true,
                                    order: [:month, :year] %>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12 col-md-6">
              <%= p.input :height, label: "Height (inches)" %>
            </div>
            <div class="col-xs-12 col-md-6">
              <%= p.input :weight, label: "Weight (kg)" %>
            </div>
          </div>

          <%= p.input :description, placeholder: 'Très gentil chien qui adore jouer au ballon. Attention, il mord de temps en temps.', input_html: { class: "small-text"} %>
          <%= p.input :food, collection:["Croquettes Royal Canin", "Croquettes Friskies", "Repas pour humains", "Graines", "Restes de poulet", "Caviar"], as: :check_boxes%>
          <%= p.input :title, label: "Title of your add", hint: "Choose a fun title to attract as many people as possible" %>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="card-white">
          <h3>Pictures</h3>
          <%= p.input :photo %>
          <%= p.input :photo_cache, as: :hidden %>
      </div>
        </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="card-white">
          <h3>Price</h3>
          <%= p.input :price, label: "Daily rental price (€)", hint: '15€ for a nice and beautiful dog, 5€ for an ugly and dangerous cat' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
          <%= p.button :submit, 'List my pet !', class: 'button'  %>
      </div>
    </div>


  <% end %>
  </div>
</div>

app/views/owner/pets/show.html.erb
<%= render 'pets/petshow' %>

app/views/pages/home.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,100,0.4) 0%, rgba(0,36,41,0.4) 50%), url('<%= asset_path('Pig.jpg') %>');">
  <div class="banner-content">
    <h1>Pet My Pet</h1>
    <p>Rent beautiful pets near where you live</p>
  </div>

  <div class="search">

      <%= simple_form_for @pet, url: pets_path, method: :get, html: {class: "form-inline"} do |p| %>
        <%= p.input :address, placeholder: 'Enter city', class: 'form-control flex-item-select', label: false %>
        <%= p.input :species, collection: Pet::SPECIES, prompt: "Select pet type", class: 'form-control flex-item-select', label: false %>
        <%= p.button :submit, 'Search', class: 'form-control flex-item-btnsearch btn btn-primary' %>
      <% end %>

  </div>
  </div>

  <div class="container text-center padded features">
      <div class="row-icons">
        <div class="col-xs-12 col-sm-6 col-md-3">
          <%= image_tag 'travel.png', class: "dog-icon"%>
          <h2>Travel without worries</h2>
          <p>Give your pet a holiday! </p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
         <%= image_tag 'money.png', class: "dog-icon"%>
          <h2>Make some quick money</h2>
          <p>No cash issues anymore.</p>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3">
        <%= image_tag 'dogicon.png', class: "dog-icon"%>
          <h2>Meet pets</h2>
          <p>Discover pet's lifestyle.</p>
        </div>
      </div>
    </div>

app/views/pages/profile.html.erb
<div class="myprofile">
  <div class ="myprofile-body">
  <div id="w">
    <div id="content" class="clearfix">
      <div id="userphoto"> <%= cl_image_tag ""%></div>
      <h1> My cool profile user</h1>

      <nav id="profiletabs">
        <ul class="clearfix">
          <li><a href="#Key info" class="sel">My info</a></li>
          <li><a href="#pets">pets</a></li>
          <li><a href="#settings">Settings</a></li>
        </ul>
      </nav>

      <section id="Key info">
        <h2> Welcome to you, lover of pets !</h2>
        <p><%= @current_user.first_name %> <%= @current_user.last_name %></p>
        <p>Email :  <%= @current_user.email %></p>
        <p>Address : <%= @current_user.address %></p>


      </section>

      <section id="pets" class="hidden">
        <p>Pets I recommend</p>

        <p class="activity">Careful Brisky, eats a lot! </p>

        <p class="activity">Such a good time with Fury</p>

        <p class="activity"> Definitely recommend to bring along Gustave if you wanna run</p>

        <p class="activity">More info to add</p>

        <p class="activity">Still more info to add</p>
      </section>


      <section id="setting" class="hidden">
        <p>Edit your user settings:</p>

        <p class="setting"><span>E-mail Address <img src="images/edit.png" alt="*Edit*"></span> change your mailm</p>

        <p class="setting"><span>Language <img src="images/edit.png" alt="*Edit*"></span> English(US)</p>

        <p class="setting"><span>Profile Status <img src="images/edit.png" alt="*Edit*"></span> Public</p>

        <p class="setting"><span>Update other stuff <img src="images/edit.png" alt="*Edit*"></span> Weekly</p>

        <p class="setting"><span>Update stuff <img src="images/edit.png" alt="*Edit*"></span> None</p>
      </section>
    </div><!-- @end #content -->
  </div><!-- @end #w -->
<script type="text/javascript">
$(function(){
  $('#profiletabs ul li a').on('click', function(e){
    e.preventDefault();
    var newcontent = $(this).attr('href');

    $('#profiletabs ul li a').removeClass('sel');
    $(this).addClass('sel');

    $('#content section').each(function(){
      if(!$(this).hasClass('hidden')) { $(this).addClass('hidden'); }
    });

    $(newcontent).removeClass('hidden');
  });
});
</script>
</div>
</div>

app/views/pets/_petshow.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-1">
      <div class="basic-info">
        <div>
          <%= image_tag @pet.photo, class: 'photo' %>
        </div>
        <div class="details">
          <h3><%= @pet.name %>'s Details</h3>

          <ul>
            <li>
              <p><span class="txt-bold">Species:</span> <%= @pet.species %></p>
            </li>
            <li>
              <p><span class="txt-bold">Gender:</span> <%= @pet.gender %></p>
            </li>
            <li>
              <p><span class="txt-bold">Birth date:</span> <%= @pet.birth_date %></p>
            </li>
            <li>
              <p><span class="txt-bold">Address:</span> <%= @pet.user.address %></p>
            </li>
          </ul>
        </div>

      </div>
    </div>

    <div class="col-xs-12 col-md-4 col-md-offset-1">
      <div class="basic-text">
        <h2><%= @pet.name %></h2>
        <h3><%= @pet.title %></h3>
        <hr>
        <p>Where: <%= @pet.address %></p>
        <p>Cost: <%= @pet.price %>€/day</p>
      </div>

<% if current_user %>
     <% if @pet.user_id != current_user.id %>
        <div class="reserve">
        <%= link_to "Pet me!", pet_bookings_path(@pet), method: 'post', class: "navbar-wagon-item navbar-wagon-button btn"%>
        </div>
      <% end %>
 <% else %>
    <div class="reserve">
    <%= link_to "Pet me!", pet_bookings_path(@pet), method: 'post', class: "navbar-wagon-item navbar-wagon-button btn"%>
    </div>
<%end%>


<% if current_user %>
    <% if @pet.user_id == current_user.id %>
    <%= link_to "Back", owner_pets_path %>
    <% end %>
 <% else %>
    <br>
    <%= link_to "Back to search results", pets_path, class: "Link" %>
<%end%>

  </div>
</div>

app/views/pets/index.html.erb
<div class="wrapper">

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <div class="container-fluid">
          <div class="row">
            <% if @pets.length > 0 %>
             <div class="title space">
            <h1><%= @message %></h1>
             </div>
            <% @pets.each do |pet| %>
            <div class="col-xs-12 col-sm-4">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= pet.photo.url.nil? ? image_path('cats_in_paris/cat_1.jpg') : pet.photo.url %>);">
                <div class="card-description">
                  <h2><%= pet.name %></h2>
                  <p><%= pet.title %></p>
                </div>

                <div class="card-price">
                  <p><%= pet.price %>€/day</p>

                </div>
                <%= link_to "", pet_path(pet), class: "card-link" %>
              </div>
            </div>
            <% end %>
            <% else %>
            <p><%= @message %></p>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pets/show.html.erb
<%= render 'petshow' %>

<h1><%= @pet.address %></h1>
<div class="banner-map" style='background-image: url("https://maps.googleapis.com/maps/api/staticmap?center=<%= @pet.address %>&zoom=15&key=AIzaSyB43mAjLeq18-tumQ8ytChKGtMM_Rr1Wx0&size=1200x600&sensor=false&maptype=roadmap&markers=color:red|<%= @pet.address %>"); height: 600px; background-size: cover;background-position: center center'>

</div>
<%#= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&key=AIzaSyB43mAjLeq18-tumQ8ytChKGtMM_Rr1Wx0&size=400x300&sensor=false&maptype=roadmap&markers=color:red|#{@current_user.address}", class: "map-font" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logopet.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
   <!--  <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->

<div class="navbar-wagon-item">
        <div class="dropdown">
        <%= current_user.first_name %>
      <!-- Profile picture and dropdown -->
            <%= image_tag "arrow.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul  class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to owner_pets_path do %>
                <i class="fa fa-paw"></i>  <%= t(".profile", default: "MyPets") %>
              <% end %>
            </li>
             <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-star"></i>  <%= t(".profile", default: "MyBookings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to t(".sign_up", default: "Sign Up"),  new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add a pet"), new_owner_pet_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>